name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Create env file'
        run: |
          touch .env
          echo NEXT_PUBLIC_API_TARGET_URL="${{ vars.NEXT_PUBLIC_API_TARGET_URL }}" >> .env
      - run: npm ci
      - run: npm run build
      - run: 7z a -tzip BUILD_${{ github.RUN_NUMBER  }}.zip ./out/*
      - uses: actions/upload-artifact@v3
        with:
          name: BUILD_${{ github.RUN_NUMBER  }}.zip
          path: BUILD_${{ github.RUN_NUMBER  }}.zip
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: BUILD_${{ github.RUN_NUMBER  }}.zip
          path: BUILD_${{ github.RUN_NUMBER  }}.zip
      - run: 7z x -y BUILD_${{ github.RUN_NUMBER  }}.zip -r -oout
      - run: ls -la
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - run: aws s3 sync ./out s3://jokes.forge.id.au
